#!/bin/bash
#
#
# Script d'installation Arch Linux
# Arch.install gpt ou Arch.install msdos
#
#
#
#
[[ $1 == "gpt" ]] && { parted /dev/sda mklabel gpt; parted -s /dev/sda unit MB mkpart primary 1 500; parted -s /dev/sda unit MB mkpart primary 500 628; parted -s /dev/sda unit MB mkpart primary 628 100%; mkfs.fat -F32 /dev/sda2 ; }
[[ $1 == "msdos" ]] && { parted /dev/sda mklabel msdos; parted -s /dev/sda unit MB mkpart primary 1 500; parted -s /dev/sda unit MB mkpart primary 500 100% ; }
mkfs.xfs /dev/sda1
numpart=$(parted /dev/sda print | tail -n 2 | head -n 1 | awk -F' ' '{print $1}')
parted -s /dev/sda set $numpart lvm on
pvcreate /dev/sda$numpart
vgcreate systemarch /dev/sda$numpart
lvcreate -L1024 -nswap systemarch 
lvcreate -l100%FREE -nroot systemarch 
mkfs.xfs /dev/systemarch/root
mkswap /dev/systemarch/swap
swapon /dev/systemarch/swap
mount /dev/systemarch/root /mnt
mkdir /mnt/boot
mount /dev/sda1 /mnt/boot
[[ $1 -eq "gpt" ]] && { mkdir /mnt/boot/efi; mount /dev/sda2 /mnt/boot/efi; }
pacstrap /mnt base base-devel efibootmgr vim btrfs-progs --noconfirm
genfstab -U -p /mnt > /mnt/etc/fstab
arch-chroot /mnt /bin/bash
cp /etc/mkinitcpio.conf /etc/mkinitcpio.conf.origin
sed -i '/^#/d' /etc/mkinitcpio.conf
sed -i 's/filesystems/lvm2 filesystems/g' /etc/mkinitcpio.conf 
mkinitcpio -p linux
pacman -S grub
[[ $1 -eq "gpt" ]] && { grub-install --target=x86_64-efi --efi-directory=/boot/efi;  grub-mkconfig -o  /boot/efi/EFI/arch/grub.cfg ; }  || { grub-install --target=i386-pc /dev/sda; }
grub-mkconfig -o /boot/grub/grub.cfg
echo "arch.localhost" > /etc/hostname 
sed -i 's/#fr_FR.UTF-8 UTF-8/fr_FR.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen
echo "LANG=fr_FR.UTF-8" > /etc/locale.conf
unlink /etc/localtime
ln -s /usr/share/zoneinfo/Europe/Paris  /etc/localtime
pacman -S bash-completion openssh sudo dhclient vim --noconfirm
nlink=$(ip a | grep ens | head -n 1 | awk -F" " '{print $2}'|tr -d ':')
echo -e "[Match]\nname=$link\n[Network]\nDHCP=yes" > /etc/systemd/network/$nlink.network
systemctl enable  systemd-networkd
echo -e "toto\ntoto" | passwd







